### ISSUE TITLE
Wrong category ID in menu API 

### ISSUE THREAD

**Issue by mokadev** [deity-io/falcon-magento2-development#22] opened 2018-12-02 11:05 UTC
**Describe the bug**
When you call /rest/V1/menu api you always got id = 0 for all categories (Test with Magento 2.2.6)

**To Reproduce**
1. Call /rest/V1/menu
2. look at the id field for each item in the returned response, it's always set to 0

**Expected behavior**
We should have the ID of the node in the response . The problem is that the id in Menu NODE is something like 'category-node-33'  so we should see this ID or just 33 in the response 

And for the URL field maybe it will be better to have just the URL path without the domain because sometimes the front domain is different from the backend domain.

**Comment by cane-lagerwaard** [comment] 2018-12-04 09:20
Hi @mokadev, thanks for reporting. This however seems to be a duplicate of https://github.com/deity-io/falcon/issues/132

I will keep this issue open as reference

**Comment by sergy-gzh** [comment] 2018-12-18 16:12
@mokadev Menu Api was reworked for 2.0 version. Issue can be closed.

**Closed by sergy-gzh** 2018-12-18 16:12 UTC
Labels: bug, fixed in 2.0
